### ***Levenshtein distance***

In [1]:
# importing library

import numpy as np

In [4]:
# two diffenrent words

seq1 = "scientist"
seq2 = "science"

In [5]:
# size of the matrix

size_x = len(seq1) + 1
size_y = len(seq2) + 1

# create a matrix with all zeros

matrix = np.zeros((size_x,size_y))

# printing the matrix

matrix

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
# filling the matrix

for x in range(size_x):
    matrix[x,0] = x

for y in range(size_y):
    matrix[0,y] = y

matrix

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [2., 0., 0., 0., 0., 0., 0., 0.],
       [3., 0., 0., 0., 0., 0., 0., 0.],
       [4., 0., 0., 0., 0., 0., 0., 0.],
       [5., 0., 0., 0., 0., 0., 0., 0.],
       [6., 0., 0., 0., 0., 0., 0., 0.],
       [7., 0., 0., 0., 0., 0., 0., 0.],
       [8., 0., 0., 0., 0., 0., 0., 0.],
       [9., 0., 0., 0., 0., 0., 0., 0.]])

In [12]:
# for each column
for x in range(1, size_x):
    # for each row
    for y in range(1, size_y):
        # check if the characters are same
        if seq1[x-1] == seq2[y-1]:
            # fill the element with the minimum of (diagonal value, first corresponding value + 1, second corresponding value + 1) 
            matrix [x,y] = min(
                matrix[x-1, y-1],
                matrix[x-1, y] + 1,                    
                matrix[x, y-1] + 1
            )
        # if characters are not same
        else:
            # fill the element with the minimum of corresponding values + 1
            matrix [x,y] = min(
                matrix[x-1,y] + 1,
                matrix[x-1,y-1] + 1,
                matrix[x,y-1] + 1
            )

# final matrix
matrix

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [1., 0., 1., 2., 3., 4., 5., 6.],
       [2., 1., 0., 1., 2., 3., 4., 5.],
       [3., 2., 1., 0., 1., 2., 3., 4.],
       [4., 3., 2., 1., 0., 1., 2., 3.],
       [5., 4., 3., 2., 1., 0., 1., 2.],
       [6., 5., 4., 3., 2., 1., 1., 2.],
       [7., 6., 5., 4., 3., 2., 2., 2.],
       [8., 7., 6., 5., 4., 3., 3., 3.],
       [9., 8., 7., 6., 5., 4., 4., 4.]])

In [13]:
# levenshtein distance
matrix[size_x - 1, size_y - 1]

4.0